-- Notes: 
-- 1. This is to replace '' (empty strings) with NULL
-- 2. Only needs to be run 1x

-- Set to 0 at beginning, Set to 1 after finishing UPDATE
SET SQL_SAFE_UPDATES = 0;

-- Update 2018 Empty strings [o]---------------------------------------------------------------------------
SET SQL_SAFE_UPDATES = 0;
DELIMITER $$
BEGIN$$
UPDATE
    cdcmortality.mortality_2018
SET
	person_id = CASE person_id WHEN '' THEN NULL ELSE person_id END,
    year_id = CASE year_id WHEN '' THEN NULL ELSE year_id END,
    resident_status = CASE resident_status WHEN '' THEN NULL ELSE resident_status END,
    edu = CASE edu WHEN '' THEN NULL ELSE edu END,
    edu_1989_rev = CASE edu_1989_rev WHEN '' THEN NULL ELSE edu_1989_rev END,
    edu_2003_rev = CASE edu_2003_rev WHEN '' THEN NULL ELSE edu_2003_rev END,
    edu_reporting_flag = CASE edu_reporting_flag WHEN '' THEN NULL ELSE edu_reporting_flag END,
    month_of_death = CASE month_of_death WHEN '' THEN NULL ELSE month_of_death END,
    sex = CASE sex WHEN '' THEN NULL ELSE sex END,
    reported_age_tmstmp_flag = CASE reported_age_tmstmp_flag WHEN '' THEN NULL ELSE reported_age_tmstmp_flag END,
    reported_age = CASE reported_age WHEN '' THEN NULL ELSE reported_age END,
    age_detail = CASE age_detail WHEN '' THEN NULL ELSE age_detail END,
    age_sub_flag = CASE age_sub_flag WHEN '' THEN NULL ELSE age_sub_flag END,
    age_recode_52 = CASE age_recode_52 WHEN '' THEN NULL ELSE age_recode_52 END,
    age_recode_27 = CASE age_recode_27 WHEN '' THEN NULL ELSE age_recode_27 END,
    age_recode_12 = CASE age_recode_12 WHEN '' THEN NULL ELSE age_recode_12 END,
    infant_age_recode_22 = CASE infant_age_recode_22 WHEN '' THEN NULL ELSE infant_age_recode_22 END,
    place_of_death_and_status = CASE place_of_death_and_status WHEN '' THEN NULL ELSE place_of_death_and_status END,
    marital_status = CASE marital_status WHEN '' THEN NULL ELSE marital_status END,
    day_of_week_of_death = CASE day_of_week_of_death WHEN '' THEN NULL ELSE day_of_week_of_death END,
    data_year = CASE data_year WHEN '' THEN NULL ELSE data_year END,
    injury_at_work = CASE injury_at_work WHEN '' THEN NULL ELSE injury_at_work END,
    manner_of_death = CASE manner_of_death WHEN '' THEN NULL ELSE manner_of_death END,
    method_of_disposition = CASE method_of_disposition WHEN '' THEN NULL ELSE method_of_disposition END,
    autopsy = CASE autopsy WHEN '' THEN NULL ELSE autopsy END,
    activity_code = CASE activity_code WHEN '' THEN NULL ELSE activity_code END,
    place_of_injury = CASE place_of_injury WHEN '' THEN NULL ELSE place_of_injury END,
    underlying_cause_of_death = CASE underlying_cause_of_death WHEN '' THEN NULL ELSE underlying_cause_of_death END,
    icd_10th_revision = CASE icd_10th_revision WHEN '' THEN NULL ELSE icd_10th_revision END,
    cause_recode_358 = CASE cause_recode_358 WHEN '' THEN NULL ELSE cause_recode_358 END,
    cause_recode_113 = CASE cause_recode_113 WHEN '' THEN NULL ELSE cause_recode_113 END,
    infant_cause_130 = CASE infant_cause_130 WHEN '' THEN NULL ELSE infant_cause_130 END,
    cause_recode_39 = CASE cause_recode_39 WHEN '' THEN NULL ELSE cause_recode_39 END,
    multiple_conditions = CASE multiple_conditions WHEN '' THEN NULL ELSE multiple_conditions END,
    number_of_entityaxis_conditions = CASE number_of_entityaxis_conditions WHEN '' THEN NULL ELSE number_of_entityaxis_conditions END,
    entityaxis_conditions_con = CASE entityaxis_conditions_con WHEN '' THEN NULL ELSE entityaxis_conditions_con END,
    entAx_condition_1st = CASE entAx_condition_1st WHEN '' THEN NULL ELSE entAx_condition_1st END,
    entAx_condition_2nd = CASE entAx_condition_2nd WHEN '' THEN NULL ELSE entAx_condition_2nd END,
    entAx_condition_3rd = CASE entAx_condition_3rd WHEN '' THEN NULL ELSE entAx_condition_3rd END,
    entAx_condition_4th = CASE entAx_condition_4th WHEN '' THEN NULL ELSE entAx_condition_4th END,
    entAx_condition_5th = CASE entAx_condition_5th WHEN '' THEN NULL ELSE entAx_condition_5th END,
    entAx_condition_6th = CASE entAx_condition_6th WHEN '' THEN NULL ELSE entAx_condition_6th END,
    entAx_condition_7th = CASE entAx_condition_7th WHEN '' THEN NULL ELSE entAx_condition_7th END,
    entAx_condition_8th = CASE entAx_condition_8th WHEN '' THEN NULL ELSE entAx_condition_8th END,
    entAx_condition_9th = CASE entAx_condition_9th WHEN '' THEN NULL ELSE entAx_condition_9th END,
    entAx_condition_10th = CASE entAx_condition_10th WHEN '' THEN NULL ELSE entAx_condition_10th END,
    entAx_condition_11th = CASE entAx_condition_11th WHEN '' THEN NULL ELSE entAx_condition_11th END,
    entAx_condition_12th = CASE entAx_condition_12th WHEN '' THEN NULL ELSE entAx_condition_12th END,
    entAx_condition_13th = CASE entAx_condition_13th WHEN '' THEN NULL ELSE entAx_condition_13th END,
    entAx_condition_14th = CASE entAx_condition_14th WHEN '' THEN NULL ELSE entAx_condition_14th END,
    entAx_condition_15th = CASE entAx_condition_15th WHEN '' THEN NULL ELSE entAx_condition_15th END,
    entAx_condition_16th = CASE entAx_condition_16th WHEN '' THEN NULL ELSE entAx_condition_16th END,
    entAx_condition_17th = CASE entAx_condition_17th WHEN '' THEN NULL ELSE entAx_condition_17th END,
    entAx_condition_18th = CASE entAx_condition_18th WHEN '' THEN NULL ELSE entAx_condition_18th END,
    entAx_condition_19th = CASE entAx_condition_19th WHEN '' THEN NULL ELSE entAx_condition_19th END,
    entAx_condition_20th = CASE entAx_condition_20th WHEN '' THEN NULL ELSE entAx_condition_20th END,
    number_of_recordaxis_conditions = CASE number_of_recordaxis_conditions WHEN '' THEN NULL ELSE number_of_recordaxis_conditions END,
    recordaxis_conditions = CASE recordaxis_conditions WHEN '' THEN NULL ELSE recordaxis_conditions END,
    recAx_condition_1st = CASE recAx_condition_1st WHEN '' THEN NULL ELSE recAx_condition_1st END,
    recAx_condition_2nd = CASE recAx_condition_2nd WHEN '' THEN NULL ELSE recAx_condition_2nd END,
    recAx_condition_3rd = CASE recAx_condition_3rd WHEN '' THEN NULL ELSE recAx_condition_3rd END,
    recAx_condition_4th = CASE recAx_condition_4th WHEN '' THEN NULL ELSE recAx_condition_4th END,
    recAx_condition_5th = CASE recAx_condition_5th WHEN '' THEN NULL ELSE recAx_condition_5th END,
    recAx_condition_6th = CASE recAx_condition_6th WHEN '' THEN NULL ELSE recAx_condition_6th END,
    recAx_condition_7th = CASE recAx_condition_7th WHEN '' THEN NULL ELSE recAx_condition_7th END,
    recAx_condition_8th = CASE recAx_condition_8th WHEN '' THEN NULL ELSE recAx_condition_8th END,
    recAx_condition_9th = CASE recAx_condition_9th WHEN '' THEN NULL ELSE recAx_condition_9th END,
    recAx_condition_10th = CASE recAx_condition_10th WHEN '' THEN NULL ELSE recAx_condition_10th END,
    recAx_condition_11th = CASE recAx_condition_11th WHEN '' THEN NULL ELSE recAx_condition_11th END,
    recAx_condition_12th = CASE recAx_condition_12th WHEN '' THEN NULL ELSE recAx_condition_12th END,
    recAx_condition_13th = CASE recAx_condition_13th WHEN '' THEN NULL ELSE recAx_condition_13th END,
    recAx_condition_14th = CASE recAx_condition_14th WHEN '' THEN NULL ELSE recAx_condition_14th END,
    recAx_condition_15th = CASE recAx_condition_15th WHEN '' THEN NULL ELSE recAx_condition_15th END,
    recAx_condition_16th = CASE recAx_condition_16th WHEN '' THEN NULL ELSE recAx_condition_16th END,
    recAx_condition_17th = CASE recAx_condition_17th WHEN '' THEN NULL ELSE recAx_condition_17th END,
    recAx_condition_18th = CASE recAx_condition_18th WHEN '' THEN NULL ELSE recAx_condition_18th END,
    recAx_condition_19th = CASE recAx_condition_19th WHEN '' THEN NULL ELSE recAx_condition_19th END,
    recAx_condition_20th = CASE recAx_condition_20th WHEN '' THEN NULL ELSE recAx_condition_20th END,
    bridged_race = CASE bridged_race WHEN '' THEN NULL ELSE bridged_race END,
    bridged_race_1 = CASE bridged_race_1 WHEN '' THEN NULL ELSE bridged_race_1 END,
    bridged_race_flag = CASE bridged_race_flag WHEN '' THEN NULL ELSE bridged_race_flag END,
    race_imputation_flag = CASE race_imputation_flag WHEN '' THEN NULL ELSE race_imputation_flag END,
    allother_races_imputed_2 = CASE allother_races_imputed_2 WHEN '' THEN NULL ELSE allother_races_imputed_2 END,
    bridged_race_recode_5 = CASE bridged_race_recode_5 WHEN '' THEN NULL ELSE bridged_race_recode_5 END,
    hispanicorigin = CASE hispanicorigin WHEN '' THEN NULL ELSE hispanicorigin END,
    hispanicorigin_bridgeracerecode = CASE hispanicorigin_bridgeracerecode WHEN '' THEN NULL ELSE hispanicorigin_bridgeracerecode END;
END$$
DELIMITER ;
SET SQL_SAFE_UPDATES = 1;


-- Update 2017 Empty strings [o]---------------------------------------------------------------------------
SET SQL_SAFE_UPDATES = 0;
DELIMITER $$
BEGIN$$
UPDATE
    cdcmortality.mortality_2017
SET
	person_id = CASE person_id WHEN '' THEN NULL ELSE person_id END,
    year_id = CASE year_id WHEN '' THEN NULL ELSE year_id END,
    resident_status = CASE resident_status WHEN '' THEN NULL ELSE resident_status END,
    edu = CASE edu WHEN '' THEN NULL ELSE edu END,
    edu_1989_rev = CASE edu_1989_rev WHEN '' THEN NULL ELSE edu_1989_rev END,
    edu_2003_rev = CASE edu_2003_rev WHEN '' THEN NULL ELSE edu_2003_rev END,
    edu_reporting_flag = CASE edu_reporting_flag WHEN '' THEN NULL ELSE edu_reporting_flag END,
    month_of_death = CASE month_of_death WHEN '' THEN NULL ELSE month_of_death END,
    sex = CASE sex WHEN '' THEN NULL ELSE sex END,
    reported_age_tmstmp_flag = CASE reported_age_tmstmp_flag WHEN '' THEN NULL ELSE reported_age_tmstmp_flag END,
    reported_age = CASE reported_age WHEN '' THEN NULL ELSE reported_age END,
    age_detail = CASE age_detail WHEN '' THEN NULL ELSE age_detail END,
    age_sub_flag = CASE age_sub_flag WHEN '' THEN NULL ELSE age_sub_flag END,
    age_recode_52 = CASE age_recode_52 WHEN '' THEN NULL ELSE age_recode_52 END,
    age_recode_27 = CASE age_recode_27 WHEN '' THEN NULL ELSE age_recode_27 END,
    age_recode_12 = CASE age_recode_12 WHEN '' THEN NULL ELSE age_recode_12 END,
    infant_age_recode_22 = CASE infant_age_recode_22 WHEN '' THEN NULL ELSE infant_age_recode_22 END,
    place_of_death_and_status = CASE place_of_death_and_status WHEN '' THEN NULL ELSE place_of_death_and_status END,
    marital_status = CASE marital_status WHEN '' THEN NULL ELSE marital_status END,
    day_of_week_of_death = CASE day_of_week_of_death WHEN '' THEN NULL ELSE day_of_week_of_death END,
    data_year = CASE data_year WHEN '' THEN NULL ELSE data_year END,
    injury_at_work = CASE injury_at_work WHEN '' THEN NULL ELSE injury_at_work END,
    manner_of_death = CASE manner_of_death WHEN '' THEN NULL ELSE manner_of_death END,
    method_of_disposition = CASE method_of_disposition WHEN '' THEN NULL ELSE method_of_disposition END,
    autopsy = CASE autopsy WHEN '' THEN NULL ELSE autopsy END,
    activity_code = CASE activity_code WHEN '' THEN NULL ELSE activity_code END,
    place_of_injury = CASE place_of_injury WHEN '' THEN NULL ELSE place_of_injury END,
    underlying_cause_of_death = CASE underlying_cause_of_death WHEN '' THEN NULL ELSE underlying_cause_of_death END,
    icd_10th_revision = CASE icd_10th_revision WHEN '' THEN NULL ELSE icd_10th_revision END,
    cause_recode_358 = CASE cause_recode_358 WHEN '' THEN NULL ELSE cause_recode_358 END,
    cause_recode_113 = CASE cause_recode_113 WHEN '' THEN NULL ELSE cause_recode_113 END,
    infant_cause_130 = CASE infant_cause_130 WHEN '' THEN NULL ELSE infant_cause_130 END,
    cause_recode_39 = CASE cause_recode_39 WHEN '' THEN NULL ELSE cause_recode_39 END,
    multiple_conditions = CASE multiple_conditions WHEN '' THEN NULL ELSE multiple_conditions END,
    number_of_entityaxis_conditions = CASE number_of_entityaxis_conditions WHEN '' THEN NULL ELSE number_of_entityaxis_conditions END,
    entityaxis_conditions_con = CASE entityaxis_conditions_con WHEN '' THEN NULL ELSE entityaxis_conditions_con END,
    entAx_condition_1st = CASE entAx_condition_1st WHEN '' THEN NULL ELSE entAx_condition_1st END,
    entAx_condition_2nd = CASE entAx_condition_2nd WHEN '' THEN NULL ELSE entAx_condition_2nd END,
    entAx_condition_3rd = CASE entAx_condition_3rd WHEN '' THEN NULL ELSE entAx_condition_3rd END,
    entAx_condition_4th = CASE entAx_condition_4th WHEN '' THEN NULL ELSE entAx_condition_4th END,
    entAx_condition_5th = CASE entAx_condition_5th WHEN '' THEN NULL ELSE entAx_condition_5th END,
    entAx_condition_6th = CASE entAx_condition_6th WHEN '' THEN NULL ELSE entAx_condition_6th END,
    entAx_condition_7th = CASE entAx_condition_7th WHEN '' THEN NULL ELSE entAx_condition_7th END,
    entAx_condition_8th = CASE entAx_condition_8th WHEN '' THEN NULL ELSE entAx_condition_8th END,
    entAx_condition_9th = CASE entAx_condition_9th WHEN '' THEN NULL ELSE entAx_condition_9th END,
    entAx_condition_10th = CASE entAx_condition_10th WHEN '' THEN NULL ELSE entAx_condition_10th END,
    entAx_condition_11th = CASE entAx_condition_11th WHEN '' THEN NULL ELSE entAx_condition_11th END,
    entAx_condition_12th = CASE entAx_condition_12th WHEN '' THEN NULL ELSE entAx_condition_12th END,
    entAx_condition_13th = CASE entAx_condition_13th WHEN '' THEN NULL ELSE entAx_condition_13th END,
    entAx_condition_14th = CASE entAx_condition_14th WHEN '' THEN NULL ELSE entAx_condition_14th END,
    entAx_condition_15th = CASE entAx_condition_15th WHEN '' THEN NULL ELSE entAx_condition_15th END,
    entAx_condition_16th = CASE entAx_condition_16th WHEN '' THEN NULL ELSE entAx_condition_16th END,
    entAx_condition_17th = CASE entAx_condition_17th WHEN '' THEN NULL ELSE entAx_condition_17th END,
    entAx_condition_18th = CASE entAx_condition_18th WHEN '' THEN NULL ELSE entAx_condition_18th END,
    entAx_condition_19th = CASE entAx_condition_19th WHEN '' THEN NULL ELSE entAx_condition_19th END,
    entAx_condition_20th = CASE entAx_condition_20th WHEN '' THEN NULL ELSE entAx_condition_20th END,
    number_of_recordaxis_conditions = CASE number_of_recordaxis_conditions WHEN '' THEN NULL ELSE number_of_recordaxis_conditions END,
    recordaxis_conditions = CASE recordaxis_conditions WHEN '' THEN NULL ELSE recordaxis_conditions END,
    recAx_condition_1st = CASE recAx_condition_1st WHEN '' THEN NULL ELSE recAx_condition_1st END,
    recAx_condition_2nd = CASE recAx_condition_2nd WHEN '' THEN NULL ELSE recAx_condition_2nd END,
    recAx_condition_3rd = CASE recAx_condition_3rd WHEN '' THEN NULL ELSE recAx_condition_3rd END,
    recAx_condition_4th = CASE recAx_condition_4th WHEN '' THEN NULL ELSE recAx_condition_4th END,
    recAx_condition_5th = CASE recAx_condition_5th WHEN '' THEN NULL ELSE recAx_condition_5th END,
    recAx_condition_6th = CASE recAx_condition_6th WHEN '' THEN NULL ELSE recAx_condition_6th END,
    recAx_condition_7th = CASE recAx_condition_7th WHEN '' THEN NULL ELSE recAx_condition_7th END,
    recAx_condition_8th = CASE recAx_condition_8th WHEN '' THEN NULL ELSE recAx_condition_8th END,
    recAx_condition_9th = CASE recAx_condition_9th WHEN '' THEN NULL ELSE recAx_condition_9th END,
    recAx_condition_10th = CASE recAx_condition_10th WHEN '' THEN NULL ELSE recAx_condition_10th END,
    recAx_condition_11th = CASE recAx_condition_11th WHEN '' THEN NULL ELSE recAx_condition_11th END,
    recAx_condition_12th = CASE recAx_condition_12th WHEN '' THEN NULL ELSE recAx_condition_12th END,
    recAx_condition_13th = CASE recAx_condition_13th WHEN '' THEN NULL ELSE recAx_condition_13th END,
    recAx_condition_14th = CASE recAx_condition_14th WHEN '' THEN NULL ELSE recAx_condition_14th END,
    recAx_condition_15th = CASE recAx_condition_15th WHEN '' THEN NULL ELSE recAx_condition_15th END,
    recAx_condition_16th = CASE recAx_condition_16th WHEN '' THEN NULL ELSE recAx_condition_16th END,
    recAx_condition_17th = CASE recAx_condition_17th WHEN '' THEN NULL ELSE recAx_condition_17th END,
    recAx_condition_18th = CASE recAx_condition_18th WHEN '' THEN NULL ELSE recAx_condition_18th END,
    recAx_condition_19th = CASE recAx_condition_19th WHEN '' THEN NULL ELSE recAx_condition_19th END,
    recAx_condition_20th = CASE recAx_condition_20th WHEN '' THEN NULL ELSE recAx_condition_20th END,
    bridged_race = CASE bridged_race WHEN '' THEN NULL ELSE bridged_race END,
    bridged_race_1 = CASE bridged_race_1 WHEN '' THEN NULL ELSE bridged_race_1 END,
    bridged_race_flag = CASE bridged_race_flag WHEN '' THEN NULL ELSE bridged_race_flag END,
    race_imputation_flag = CASE race_imputation_flag WHEN '' THEN NULL ELSE race_imputation_flag END,
    allother_races_imputed_2 = CASE allother_races_imputed_2 WHEN '' THEN NULL ELSE allother_races_imputed_2 END,
    bridged_race_recode_5 = CASE bridged_race_recode_5 WHEN '' THEN NULL ELSE bridged_race_recode_5 END,
    hispanicorigin = CASE hispanicorigin WHEN '' THEN NULL ELSE hispanicorigin END,
    hispanicorigin_bridgeracerecode = CASE hispanicorigin_bridgeracerecode WHEN '' THEN NULL ELSE hispanicorigin_bridgeracerecode END;
END$$
DELIMITER ;
SET SQL_SAFE_UPDATES = 1;


-- Update 2016 Empty strings done [o]---------------------------------------------------------------------------
SET SQL_SAFE_UPDATES = 0;
DELIMITER $$
BEGIN$$
UPDATE
    cdcmortality.mortality_2016
SET
	person_id = CASE person_id WHEN '' THEN NULL ELSE person_id END,
    year_id = CASE year_id WHEN '' THEN NULL ELSE year_id END,
    resident_status = CASE resident_status WHEN '' THEN NULL ELSE resident_status END,
    edu = CASE edu WHEN '' THEN NULL ELSE edu END,
    edu_1989_rev = CASE edu_1989_rev WHEN '' THEN NULL ELSE edu_1989_rev END,
    edu_2003_rev = CASE edu_2003_rev WHEN '' THEN NULL ELSE edu_2003_rev END,
    edu_reporting_flag = CASE edu_reporting_flag WHEN '' THEN NULL ELSE edu_reporting_flag END,
    month_of_death = CASE month_of_death WHEN '' THEN NULL ELSE month_of_death END,
    sex = CASE sex WHEN '' THEN NULL ELSE sex END,
    reported_age_tmstmp_flag = CASE reported_age_tmstmp_flag WHEN '' THEN NULL ELSE reported_age_tmstmp_flag END,
    reported_age = CASE reported_age WHEN '' THEN NULL ELSE reported_age END,
    age_detail = CASE age_detail WHEN '' THEN NULL ELSE age_detail END,
    age_sub_flag = CASE age_sub_flag WHEN '' THEN NULL ELSE age_sub_flag END,
    age_recode_52 = CASE age_recode_52 WHEN '' THEN NULL ELSE age_recode_52 END,
    age_recode_27 = CASE age_recode_27 WHEN '' THEN NULL ELSE age_recode_27 END,
    age_recode_12 = CASE age_recode_12 WHEN '' THEN NULL ELSE age_recode_12 END,
    infant_age_recode_22 = CASE infant_age_recode_22 WHEN '' THEN NULL ELSE infant_age_recode_22 END,
    place_of_death_and_status = CASE place_of_death_and_status WHEN '' THEN NULL ELSE place_of_death_and_status END,
    marital_status = CASE marital_status WHEN '' THEN NULL ELSE marital_status END,
    day_of_week_of_death = CASE day_of_week_of_death WHEN '' THEN NULL ELSE day_of_week_of_death END,
    data_year = CASE data_year WHEN '' THEN NULL ELSE data_year END,
    injury_at_work = CASE injury_at_work WHEN '' THEN NULL ELSE injury_at_work END,
    manner_of_death = CASE manner_of_death WHEN '' THEN NULL ELSE manner_of_death END,
    method_of_disposition = CASE method_of_disposition WHEN '' THEN NULL ELSE method_of_disposition END,
    autopsy = CASE autopsy WHEN '' THEN NULL ELSE autopsy END,
    activity_code = CASE activity_code WHEN '' THEN NULL ELSE activity_code END,
    place_of_injury = CASE place_of_injury WHEN '' THEN NULL ELSE place_of_injury END,
    underlying_cause_of_death = CASE underlying_cause_of_death WHEN '' THEN NULL ELSE underlying_cause_of_death END,
    icd_10th_revision = CASE icd_10th_revision WHEN '' THEN NULL ELSE icd_10th_revision END,
    cause_recode_358 = CASE cause_recode_358 WHEN '' THEN NULL ELSE cause_recode_358 END,
    cause_recode_113 = CASE cause_recode_113 WHEN '' THEN NULL ELSE cause_recode_113 END,
    infant_cause_130 = CASE infant_cause_130 WHEN '' THEN NULL ELSE infant_cause_130 END,
    cause_recode_39 = CASE cause_recode_39 WHEN '' THEN NULL ELSE cause_recode_39 END,
    multiple_conditions = CASE multiple_conditions WHEN '' THEN NULL ELSE multiple_conditions END,
    number_of_entityaxis_conditions = CASE number_of_entityaxis_conditions WHEN '' THEN NULL ELSE number_of_entityaxis_conditions END,
    entityaxis_conditions_con = CASE entityaxis_conditions_con WHEN '' THEN NULL ELSE entityaxis_conditions_con END,
    entAx_condition_1st = CASE entAx_condition_1st WHEN '' THEN NULL ELSE entAx_condition_1st END,
    entAx_condition_2nd = CASE entAx_condition_2nd WHEN '' THEN NULL ELSE entAx_condition_2nd END,
    entAx_condition_3rd = CASE entAx_condition_3rd WHEN '' THEN NULL ELSE entAx_condition_3rd END,
    entAx_condition_4th = CASE entAx_condition_4th WHEN '' THEN NULL ELSE entAx_condition_4th END,
    entAx_condition_5th = CASE entAx_condition_5th WHEN '' THEN NULL ELSE entAx_condition_5th END,
    entAx_condition_6th = CASE entAx_condition_6th WHEN '' THEN NULL ELSE entAx_condition_6th END,
    entAx_condition_7th = CASE entAx_condition_7th WHEN '' THEN NULL ELSE entAx_condition_7th END,
    entAx_condition_8th = CASE entAx_condition_8th WHEN '' THEN NULL ELSE entAx_condition_8th END,
    entAx_condition_9th = CASE entAx_condition_9th WHEN '' THEN NULL ELSE entAx_condition_9th END,
    entAx_condition_10th = CASE entAx_condition_10th WHEN '' THEN NULL ELSE entAx_condition_10th END,
    entAx_condition_11th = CASE entAx_condition_11th WHEN '' THEN NULL ELSE entAx_condition_11th END,
    entAx_condition_12th = CASE entAx_condition_12th WHEN '' THEN NULL ELSE entAx_condition_12th END,
    entAx_condition_13th = CASE entAx_condition_13th WHEN '' THEN NULL ELSE entAx_condition_13th END,
    entAx_condition_14th = CASE entAx_condition_14th WHEN '' THEN NULL ELSE entAx_condition_14th END,
    entAx_condition_15th = CASE entAx_condition_15th WHEN '' THEN NULL ELSE entAx_condition_15th END,
    entAx_condition_16th = CASE entAx_condition_16th WHEN '' THEN NULL ELSE entAx_condition_16th END,
    entAx_condition_17th = CASE entAx_condition_17th WHEN '' THEN NULL ELSE entAx_condition_17th END,
    entAx_condition_18th = CASE entAx_condition_18th WHEN '' THEN NULL ELSE entAx_condition_18th END,
    entAx_condition_19th = CASE entAx_condition_19th WHEN '' THEN NULL ELSE entAx_condition_19th END,
    entAx_condition_20th = CASE entAx_condition_20th WHEN '' THEN NULL ELSE entAx_condition_20th END,
    number_of_recordaxis_conditions = CASE number_of_recordaxis_conditions WHEN '' THEN NULL ELSE number_of_recordaxis_conditions END,
    recordaxis_conditions = CASE recordaxis_conditions WHEN '' THEN NULL ELSE recordaxis_conditions END,
    recAx_condition_1st = CASE recAx_condition_1st WHEN '' THEN NULL ELSE recAx_condition_1st END,
    recAx_condition_2nd = CASE recAx_condition_2nd WHEN '' THEN NULL ELSE recAx_condition_2nd END,
    recAx_condition_3rd = CASE recAx_condition_3rd WHEN '' THEN NULL ELSE recAx_condition_3rd END,
    recAx_condition_4th = CASE recAx_condition_4th WHEN '' THEN NULL ELSE recAx_condition_4th END,
    recAx_condition_5th = CASE recAx_condition_5th WHEN '' THEN NULL ELSE recAx_condition_5th END,
    recAx_condition_6th = CASE recAx_condition_6th WHEN '' THEN NULL ELSE recAx_condition_6th END,
    recAx_condition_7th = CASE recAx_condition_7th WHEN '' THEN NULL ELSE recAx_condition_7th END,
    recAx_condition_8th = CASE recAx_condition_8th WHEN '' THEN NULL ELSE recAx_condition_8th END,
    recAx_condition_9th = CASE recAx_condition_9th WHEN '' THEN NULL ELSE recAx_condition_9th END,
    recAx_condition_10th = CASE recAx_condition_10th WHEN '' THEN NULL ELSE recAx_condition_10th END,
    recAx_condition_11th = CASE recAx_condition_11th WHEN '' THEN NULL ELSE recAx_condition_11th END,
    recAx_condition_12th = CASE recAx_condition_12th WHEN '' THEN NULL ELSE recAx_condition_12th END,
    recAx_condition_13th = CASE recAx_condition_13th WHEN '' THEN NULL ELSE recAx_condition_13th END,
    recAx_condition_14th = CASE recAx_condition_14th WHEN '' THEN NULL ELSE recAx_condition_14th END,
    recAx_condition_15th = CASE recAx_condition_15th WHEN '' THEN NULL ELSE recAx_condition_15th END,
    recAx_condition_16th = CASE recAx_condition_16th WHEN '' THEN NULL ELSE recAx_condition_16th END,
    recAx_condition_17th = CASE recAx_condition_17th WHEN '' THEN NULL ELSE recAx_condition_17th END,
    recAx_condition_18th = CASE recAx_condition_18th WHEN '' THEN NULL ELSE recAx_condition_18th END,
    recAx_condition_19th = CASE recAx_condition_19th WHEN '' THEN NULL ELSE recAx_condition_19th END,
    recAx_condition_20th = CASE recAx_condition_20th WHEN '' THEN NULL ELSE recAx_condition_20th END,
    bridged_race = CASE bridged_race WHEN '' THEN NULL ELSE bridged_race END,
    bridged_race_1 = CASE bridged_race_1 WHEN '' THEN NULL ELSE bridged_race_1 END,
    bridged_race_flag = CASE bridged_race_flag WHEN '' THEN NULL ELSE bridged_race_flag END,
    race_imputation_flag = CASE race_imputation_flag WHEN '' THEN NULL ELSE race_imputation_flag END,
    allother_races_imputed_2 = CASE allother_races_imputed_2 WHEN '' THEN NULL ELSE allother_races_imputed_2 END,
    bridged_race_recode_5 = CASE bridged_race_recode_5 WHEN '' THEN NULL ELSE bridged_race_recode_5 END,
    hispanicorigin = CASE hispanicorigin WHEN '' THEN NULL ELSE hispanicorigin END,
    hispanicorigin_bridgeracerecode = CASE hispanicorigin_bridgeracerecode WHEN '' THEN NULL ELSE hispanicorigin_bridgeracerecode END;
END$$
DELIMITER ;
SET SQL_SAFE_UPDATES = 1;


-- Update 2015 Empty strings done [o]---------------------------------------------------------------------------
SET SQL_SAFE_UPDATES = 0;
DELIMITER $$
BEGIN$$
UPDATE
    cdcmortality.mortality_2015
SET
	person_id = CASE person_id WHEN '' THEN NULL ELSE person_id END,
    year_id = CASE year_id WHEN '' THEN NULL ELSE year_id END,
    resident_status = CASE resident_status WHEN '' THEN NULL ELSE resident_status END,
    edu = CASE edu WHEN '' THEN NULL ELSE edu END,
    edu_1989_rev = CASE edu_1989_rev WHEN '' THEN NULL ELSE edu_1989_rev END,
    edu_2003_rev = CASE edu_2003_rev WHEN '' THEN NULL ELSE edu_2003_rev END,
    edu_reporting_flag = CASE edu_reporting_flag WHEN '' THEN NULL ELSE edu_reporting_flag END,
    month_of_death = CASE month_of_death WHEN '' THEN NULL ELSE month_of_death END,
    sex = CASE sex WHEN '' THEN NULL ELSE sex END,
    reported_age_tmstmp_flag = CASE reported_age_tmstmp_flag WHEN '' THEN NULL ELSE reported_age_tmstmp_flag END,
    reported_age = CASE reported_age WHEN '' THEN NULL ELSE reported_age END,
    age_detail = CASE age_detail WHEN '' THEN NULL ELSE age_detail END,
    age_sub_flag = CASE age_sub_flag WHEN '' THEN NULL ELSE age_sub_flag END,
    age_recode_52 = CASE age_recode_52 WHEN '' THEN NULL ELSE age_recode_52 END,
    age_recode_27 = CASE age_recode_27 WHEN '' THEN NULL ELSE age_recode_27 END,
    age_recode_12 = CASE age_recode_12 WHEN '' THEN NULL ELSE age_recode_12 END,
    infant_age_recode_22 = CASE infant_age_recode_22 WHEN '' THEN NULL ELSE infant_age_recode_22 END,
    place_of_death_and_status = CASE place_of_death_and_status WHEN '' THEN NULL ELSE place_of_death_and_status END,
    marital_status = CASE marital_status WHEN '' THEN NULL ELSE marital_status END,
    day_of_week_of_death = CASE day_of_week_of_death WHEN '' THEN NULL ELSE day_of_week_of_death END,
    data_year = CASE data_year WHEN '' THEN NULL ELSE data_year END,
    injury_at_work = CASE injury_at_work WHEN '' THEN NULL ELSE injury_at_work END,
    manner_of_death = CASE manner_of_death WHEN '' THEN NULL ELSE manner_of_death END,
    method_of_disposition = CASE method_of_disposition WHEN '' THEN NULL ELSE method_of_disposition END,
    autopsy = CASE autopsy WHEN '' THEN NULL ELSE autopsy END,
    activity_code = CASE activity_code WHEN '' THEN NULL ELSE activity_code END,
    place_of_injury = CASE place_of_injury WHEN '' THEN NULL ELSE place_of_injury END,
    underlying_cause_of_death = CASE underlying_cause_of_death WHEN '' THEN NULL ELSE underlying_cause_of_death END,
    icd_10th_revision = CASE icd_10th_revision WHEN '' THEN NULL ELSE icd_10th_revision END,
    cause_recode_358 = CASE cause_recode_358 WHEN '' THEN NULL ELSE cause_recode_358 END,
    cause_recode_113 = CASE cause_recode_113 WHEN '' THEN NULL ELSE cause_recode_113 END,
    infant_cause_130 = CASE infant_cause_130 WHEN '' THEN NULL ELSE infant_cause_130 END,
    cause_recode_39 = CASE cause_recode_39 WHEN '' THEN NULL ELSE cause_recode_39 END,
    multiple_conditions = CASE multiple_conditions WHEN '' THEN NULL ELSE multiple_conditions END,
    number_of_entityaxis_conditions = CASE number_of_entityaxis_conditions WHEN '' THEN NULL ELSE number_of_entityaxis_conditions END,
    entityaxis_conditions_con = CASE entityaxis_conditions_con WHEN '' THEN NULL ELSE entityaxis_conditions_con END,
    entAx_condition_1st = CASE entAx_condition_1st WHEN '' THEN NULL ELSE entAx_condition_1st END,
    entAx_condition_2nd = CASE entAx_condition_2nd WHEN '' THEN NULL ELSE entAx_condition_2nd END,
    entAx_condition_3rd = CASE entAx_condition_3rd WHEN '' THEN NULL ELSE entAx_condition_3rd END,
    entAx_condition_4th = CASE entAx_condition_4th WHEN '' THEN NULL ELSE entAx_condition_4th END,
    entAx_condition_5th = CASE entAx_condition_5th WHEN '' THEN NULL ELSE entAx_condition_5th END,
    entAx_condition_6th = CASE entAx_condition_6th WHEN '' THEN NULL ELSE entAx_condition_6th END,
    entAx_condition_7th = CASE entAx_condition_7th WHEN '' THEN NULL ELSE entAx_condition_7th END,
    entAx_condition_8th = CASE entAx_condition_8th WHEN '' THEN NULL ELSE entAx_condition_8th END,
    entAx_condition_9th = CASE entAx_condition_9th WHEN '' THEN NULL ELSE entAx_condition_9th END,
    entAx_condition_10th = CASE entAx_condition_10th WHEN '' THEN NULL ELSE entAx_condition_10th END,
    entAx_condition_11th = CASE entAx_condition_11th WHEN '' THEN NULL ELSE entAx_condition_11th END,
    entAx_condition_12th = CASE entAx_condition_12th WHEN '' THEN NULL ELSE entAx_condition_12th END,
    entAx_condition_13th = CASE entAx_condition_13th WHEN '' THEN NULL ELSE entAx_condition_13th END,
    entAx_condition_14th = CASE entAx_condition_14th WHEN '' THEN NULL ELSE entAx_condition_14th END,
    entAx_condition_15th = CASE entAx_condition_15th WHEN '' THEN NULL ELSE entAx_condition_15th END,
    entAx_condition_16th = CASE entAx_condition_16th WHEN '' THEN NULL ELSE entAx_condition_16th END,
    entAx_condition_17th = CASE entAx_condition_17th WHEN '' THEN NULL ELSE entAx_condition_17th END,
    entAx_condition_18th = CASE entAx_condition_18th WHEN '' THEN NULL ELSE entAx_condition_18th END,
    entAx_condition_19th = CASE entAx_condition_19th WHEN '' THEN NULL ELSE entAx_condition_19th END,
    entAx_condition_20th = CASE entAx_condition_20th WHEN '' THEN NULL ELSE entAx_condition_20th END,
    number_of_recordaxis_conditions = CASE number_of_recordaxis_conditions WHEN '' THEN NULL ELSE number_of_recordaxis_conditions END,
    recordaxis_conditions = CASE recordaxis_conditions WHEN '' THEN NULL ELSE recordaxis_conditions END,
    recAx_condition_1st = CASE recAx_condition_1st WHEN '' THEN NULL ELSE recAx_condition_1st END,
    recAx_condition_2nd = CASE recAx_condition_2nd WHEN '' THEN NULL ELSE recAx_condition_2nd END,
    recAx_condition_3rd = CASE recAx_condition_3rd WHEN '' THEN NULL ELSE recAx_condition_3rd END,
    recAx_condition_4th = CASE recAx_condition_4th WHEN '' THEN NULL ELSE recAx_condition_4th END,
    recAx_condition_5th = CASE recAx_condition_5th WHEN '' THEN NULL ELSE recAx_condition_5th END,
    recAx_condition_6th = CASE recAx_condition_6th WHEN '' THEN NULL ELSE recAx_condition_6th END,
    recAx_condition_7th = CASE recAx_condition_7th WHEN '' THEN NULL ELSE recAx_condition_7th END,
    recAx_condition_8th = CASE recAx_condition_8th WHEN '' THEN NULL ELSE recAx_condition_8th END,
    recAx_condition_9th = CASE recAx_condition_9th WHEN '' THEN NULL ELSE recAx_condition_9th END,
    recAx_condition_10th = CASE recAx_condition_10th WHEN '' THEN NULL ELSE recAx_condition_10th END,
    recAx_condition_11th = CASE recAx_condition_11th WHEN '' THEN NULL ELSE recAx_condition_11th END,
    recAx_condition_12th = CASE recAx_condition_12th WHEN '' THEN NULL ELSE recAx_condition_12th END,
    recAx_condition_13th = CASE recAx_condition_13th WHEN '' THEN NULL ELSE recAx_condition_13th END,
    recAx_condition_14th = CASE recAx_condition_14th WHEN '' THEN NULL ELSE recAx_condition_14th END,
    recAx_condition_15th = CASE recAx_condition_15th WHEN '' THEN NULL ELSE recAx_condition_15th END,
    recAx_condition_16th = CASE recAx_condition_16th WHEN '' THEN NULL ELSE recAx_condition_16th END,
    recAx_condition_17th = CASE recAx_condition_17th WHEN '' THEN NULL ELSE recAx_condition_17th END,
    recAx_condition_18th = CASE recAx_condition_18th WHEN '' THEN NULL ELSE recAx_condition_18th END,
    recAx_condition_19th = CASE recAx_condition_19th WHEN '' THEN NULL ELSE recAx_condition_19th END,
    recAx_condition_20th = CASE recAx_condition_20th WHEN '' THEN NULL ELSE recAx_condition_20th END,
    bridged_race = CASE bridged_race WHEN '' THEN NULL ELSE bridged_race END,
    bridged_race_1 = CASE bridged_race_1 WHEN '' THEN NULL ELSE bridged_race_1 END,
    bridged_race_flag = CASE bridged_race_flag WHEN '' THEN NULL ELSE bridged_race_flag END,
    race_imputation_flag = CASE race_imputation_flag WHEN '' THEN NULL ELSE race_imputation_flag END,
    allother_races_imputed_2 = CASE allother_races_imputed_2 WHEN '' THEN NULL ELSE allother_races_imputed_2 END,
    bridged_race_recode_5 = CASE bridged_race_recode_5 WHEN '' THEN NULL ELSE bridged_race_recode_5 END,
    hispanicorigin = CASE hispanicorigin WHEN '' THEN NULL ELSE hispanicorigin END,
    hispanicorigin_bridgeracerecode = CASE hispanicorigin_bridgeracerecode WHEN '' THEN NULL ELSE hispanicorigin_bridgeracerecode END;
END$$
DELIMITER ;
SET SQL_SAFE_UPDATES = 1;

-- Update 2014 Empty strings [o]---------------------------------------------------------------------------
SET SQL_SAFE_UPDATES = 0;
DELIMITER $$
BEGIN$$
UPDATE
    cdcmortality.mortality_2014
SET
	person_id = CASE person_id WHEN '' THEN NULL ELSE person_id END,
    year_id = CASE year_id WHEN '' THEN NULL ELSE year_id END,
    resident_status = CASE resident_status WHEN '' THEN NULL ELSE resident_status END,
    edu = CASE edu WHEN '' THEN NULL ELSE edu END,
    edu_1989_rev = CASE edu_1989_rev WHEN '' THEN NULL ELSE edu_1989_rev END,
    edu_2003_rev = CASE edu_2003_rev WHEN '' THEN NULL ELSE edu_2003_rev END,
    edu_reporting_flag = CASE edu_reporting_flag WHEN '' THEN NULL ELSE edu_reporting_flag END,
    month_of_death = CASE month_of_death WHEN '' THEN NULL ELSE month_of_death END,
    sex = CASE sex WHEN '' THEN NULL ELSE sex END,
    reported_age_tmstmp_flag = CASE reported_age_tmstmp_flag WHEN '' THEN NULL ELSE reported_age_tmstmp_flag END,
    reported_age = CASE reported_age WHEN '' THEN NULL ELSE reported_age END,
    age_detail = CASE age_detail WHEN '' THEN NULL ELSE age_detail END,
    age_sub_flag = CASE age_sub_flag WHEN '' THEN NULL ELSE age_sub_flag END,
    age_recode_52 = CASE age_recode_52 WHEN '' THEN NULL ELSE age_recode_52 END,
    age_recode_27 = CASE age_recode_27 WHEN '' THEN NULL ELSE age_recode_27 END,
    age_recode_12 = CASE age_recode_12 WHEN '' THEN NULL ELSE age_recode_12 END,
    infant_age_recode_22 = CASE infant_age_recode_22 WHEN '' THEN NULL ELSE infant_age_recode_22 END,
    place_of_death_and_status = CASE place_of_death_and_status WHEN '' THEN NULL ELSE place_of_death_and_status END,
    marital_status = CASE marital_status WHEN '' THEN NULL ELSE marital_status END,
    day_of_week_of_death = CASE day_of_week_of_death WHEN '' THEN NULL ELSE day_of_week_of_death END,
    data_year = CASE data_year WHEN '' THEN NULL ELSE data_year END,
    injury_at_work = CASE injury_at_work WHEN '' THEN NULL ELSE injury_at_work END,
    manner_of_death = CASE manner_of_death WHEN '' THEN NULL ELSE manner_of_death END,
    method_of_disposition = CASE method_of_disposition WHEN '' THEN NULL ELSE method_of_disposition END,
    autopsy = CASE autopsy WHEN '' THEN NULL ELSE autopsy END,
    activity_code = CASE activity_code WHEN '' THEN NULL ELSE activity_code END,
    place_of_injury = CASE place_of_injury WHEN '' THEN NULL ELSE place_of_injury END,
    underlying_cause_of_death = CASE underlying_cause_of_death WHEN '' THEN NULL ELSE underlying_cause_of_death END,
    icd_10th_revision = CASE icd_10th_revision WHEN '' THEN NULL ELSE icd_10th_revision END,
    cause_recode_358 = CASE cause_recode_358 WHEN '' THEN NULL ELSE cause_recode_358 END,
    cause_recode_113 = CASE cause_recode_113 WHEN '' THEN NULL ELSE cause_recode_113 END,
    infant_cause_130 = CASE infant_cause_130 WHEN '' THEN NULL ELSE infant_cause_130 END,
    cause_recode_39 = CASE cause_recode_39 WHEN '' THEN NULL ELSE cause_recode_39 END,
    multiple_conditions = CASE multiple_conditions WHEN '' THEN NULL ELSE multiple_conditions END,
    number_of_entityaxis_conditions = CASE number_of_entityaxis_conditions WHEN '' THEN NULL ELSE number_of_entityaxis_conditions END,
    entityaxis_conditions_con = CASE entityaxis_conditions_con WHEN '' THEN NULL ELSE entityaxis_conditions_con END,
    entAx_condition_1st = CASE entAx_condition_1st WHEN '' THEN NULL ELSE entAx_condition_1st END,
    entAx_condition_2nd = CASE entAx_condition_2nd WHEN '' THEN NULL ELSE entAx_condition_2nd END,
    entAx_condition_3rd = CASE entAx_condition_3rd WHEN '' THEN NULL ELSE entAx_condition_3rd END,
    entAx_condition_4th = CASE entAx_condition_4th WHEN '' THEN NULL ELSE entAx_condition_4th END,
    entAx_condition_5th = CASE entAx_condition_5th WHEN '' THEN NULL ELSE entAx_condition_5th END,
    entAx_condition_6th = CASE entAx_condition_6th WHEN '' THEN NULL ELSE entAx_condition_6th END,
    entAx_condition_7th = CASE entAx_condition_7th WHEN '' THEN NULL ELSE entAx_condition_7th END,
    entAx_condition_8th = CASE entAx_condition_8th WHEN '' THEN NULL ELSE entAx_condition_8th END,
    entAx_condition_9th = CASE entAx_condition_9th WHEN '' THEN NULL ELSE entAx_condition_9th END,
    entAx_condition_10th = CASE entAx_condition_10th WHEN '' THEN NULL ELSE entAx_condition_10th END,
    entAx_condition_11th = CASE entAx_condition_11th WHEN '' THEN NULL ELSE entAx_condition_11th END,
    entAx_condition_12th = CASE entAx_condition_12th WHEN '' THEN NULL ELSE entAx_condition_12th END,
    entAx_condition_13th = CASE entAx_condition_13th WHEN '' THEN NULL ELSE entAx_condition_13th END,
    entAx_condition_14th = CASE entAx_condition_14th WHEN '' THEN NULL ELSE entAx_condition_14th END,
    entAx_condition_15th = CASE entAx_condition_15th WHEN '' THEN NULL ELSE entAx_condition_15th END,
    entAx_condition_16th = CASE entAx_condition_16th WHEN '' THEN NULL ELSE entAx_condition_16th END,
    entAx_condition_17th = CASE entAx_condition_17th WHEN '' THEN NULL ELSE entAx_condition_17th END,
    entAx_condition_18th = CASE entAx_condition_18th WHEN '' THEN NULL ELSE entAx_condition_18th END,
    entAx_condition_19th = CASE entAx_condition_19th WHEN '' THEN NULL ELSE entAx_condition_19th END,
    entAx_condition_20th = CASE entAx_condition_20th WHEN '' THEN NULL ELSE entAx_condition_20th END,
    number_of_recordaxis_conditions = CASE number_of_recordaxis_conditions WHEN '' THEN NULL ELSE number_of_recordaxis_conditions END,
    recordaxis_conditions = CASE recordaxis_conditions WHEN '' THEN NULL ELSE recordaxis_conditions END,
    recAx_condition_1st = CASE recAx_condition_1st WHEN '' THEN NULL ELSE recAx_condition_1st END,
    recAx_condition_2nd = CASE recAx_condition_2nd WHEN '' THEN NULL ELSE recAx_condition_2nd END,
    recAx_condition_3rd = CASE recAx_condition_3rd WHEN '' THEN NULL ELSE recAx_condition_3rd END,
    recAx_condition_4th = CASE recAx_condition_4th WHEN '' THEN NULL ELSE recAx_condition_4th END,
    recAx_condition_5th = CASE recAx_condition_5th WHEN '' THEN NULL ELSE recAx_condition_5th END,
    recAx_condition_6th = CASE recAx_condition_6th WHEN '' THEN NULL ELSE recAx_condition_6th END,
    recAx_condition_7th = CASE recAx_condition_7th WHEN '' THEN NULL ELSE recAx_condition_7th END,
    recAx_condition_8th = CASE recAx_condition_8th WHEN '' THEN NULL ELSE recAx_condition_8th END,
    recAx_condition_9th = CASE recAx_condition_9th WHEN '' THEN NULL ELSE recAx_condition_9th END,
    recAx_condition_10th = CASE recAx_condition_10th WHEN '' THEN NULL ELSE recAx_condition_10th END,
    recAx_condition_11th = CASE recAx_condition_11th WHEN '' THEN NULL ELSE recAx_condition_11th END,
    recAx_condition_12th = CASE recAx_condition_12th WHEN '' THEN NULL ELSE recAx_condition_12th END,
    recAx_condition_13th = CASE recAx_condition_13th WHEN '' THEN NULL ELSE recAx_condition_13th END,
    recAx_condition_14th = CASE recAx_condition_14th WHEN '' THEN NULL ELSE recAx_condition_14th END,
    recAx_condition_15th = CASE recAx_condition_15th WHEN '' THEN NULL ELSE recAx_condition_15th END,
    recAx_condition_16th = CASE recAx_condition_16th WHEN '' THEN NULL ELSE recAx_condition_16th END,
    recAx_condition_17th = CASE recAx_condition_17th WHEN '' THEN NULL ELSE recAx_condition_17th END,
    recAx_condition_18th = CASE recAx_condition_18th WHEN '' THEN NULL ELSE recAx_condition_18th END,
    recAx_condition_19th = CASE recAx_condition_19th WHEN '' THEN NULL ELSE recAx_condition_19th END,
    recAx_condition_20th = CASE recAx_condition_20th WHEN '' THEN NULL ELSE recAx_condition_20th END,
    bridged_race = CASE bridged_race WHEN '' THEN NULL ELSE bridged_race END,
    bridged_race_1 = CASE bridged_race_1 WHEN '' THEN NULL ELSE bridged_race_1 END,
    bridged_race_flag = CASE bridged_race_flag WHEN '' THEN NULL ELSE bridged_race_flag END,
    race_imputation_flag = CASE race_imputation_flag WHEN '' THEN NULL ELSE race_imputation_flag END,
    allother_races_imputed_2 = CASE allother_races_imputed_2 WHEN '' THEN NULL ELSE allother_races_imputed_2 END,
    bridged_race_recode_5 = CASE bridged_race_recode_5 WHEN '' THEN NULL ELSE bridged_race_recode_5 END,
    hispanicorigin = CASE hispanicorigin WHEN '' THEN NULL ELSE hispanicorigin END,
    hispanicorigin_bridgeracerecode = CASE hispanicorigin_bridgeracerecode WHEN '' THEN NULL ELSE hispanicorigin_bridgeracerecode END;
END$$
DELIMITER ;
SET SQL_SAFE_UPDATES = 1;

-- Update 2013 Empty strings [o]---------------------------------------------------------------------------
SET SQL_SAFE_UPDATES = 0;
DELIMITER $$
BEGIN$$
UPDATE
    cdcmortality.mortality_2013
SET
	person_id = CASE person_id WHEN '' THEN NULL ELSE person_id END,
    year_id = CASE year_id WHEN '' THEN NULL ELSE year_id END,
    resident_status = CASE resident_status WHEN '' THEN NULL ELSE resident_status END,
    edu = CASE edu WHEN '' THEN NULL ELSE edu END,
    edu_1989_rev = CASE edu_1989_rev WHEN '' THEN NULL ELSE edu_1989_rev END,
    edu_2003_rev = CASE edu_2003_rev WHEN '' THEN NULL ELSE edu_2003_rev END,
    edu_reporting_flag = CASE edu_reporting_flag WHEN '' THEN NULL ELSE edu_reporting_flag END,
    month_of_death = CASE month_of_death WHEN '' THEN NULL ELSE month_of_death END,
    sex = CASE sex WHEN '' THEN NULL ELSE sex END,
    reported_age_tmstmp_flag = CASE reported_age_tmstmp_flag WHEN '' THEN NULL ELSE reported_age_tmstmp_flag END,
    reported_age = CASE reported_age WHEN '' THEN NULL ELSE reported_age END,
    age_detail = CASE age_detail WHEN '' THEN NULL ELSE age_detail END,
    age_sub_flag = CASE age_sub_flag WHEN '' THEN NULL ELSE age_sub_flag END,
    age_recode_52 = CASE age_recode_52 WHEN '' THEN NULL ELSE age_recode_52 END,
    age_recode_27 = CASE age_recode_27 WHEN '' THEN NULL ELSE age_recode_27 END,
    age_recode_12 = CASE age_recode_12 WHEN '' THEN NULL ELSE age_recode_12 END,
    infant_age_recode_22 = CASE infant_age_recode_22 WHEN '' THEN NULL ELSE infant_age_recode_22 END,
    place_of_death_and_status = CASE place_of_death_and_status WHEN '' THEN NULL ELSE place_of_death_and_status END,
    marital_status = CASE marital_status WHEN '' THEN NULL ELSE marital_status END,
    day_of_week_of_death = CASE day_of_week_of_death WHEN '' THEN NULL ELSE day_of_week_of_death END,
    data_year = CASE data_year WHEN '' THEN NULL ELSE data_year END,
    injury_at_work = CASE injury_at_work WHEN '' THEN NULL ELSE injury_at_work END,
    manner_of_death = CASE manner_of_death WHEN '' THEN NULL ELSE manner_of_death END,
    method_of_disposition = CASE method_of_disposition WHEN '' THEN NULL ELSE method_of_disposition END,
    autopsy = CASE autopsy WHEN '' THEN NULL ELSE autopsy END,
    activity_code = CASE activity_code WHEN '' THEN NULL ELSE activity_code END,
    place_of_injury = CASE place_of_injury WHEN '' THEN NULL ELSE place_of_injury END,
    underlying_cause_of_death = CASE underlying_cause_of_death WHEN '' THEN NULL ELSE underlying_cause_of_death END,
    icd_10th_revision = CASE icd_10th_revision WHEN '' THEN NULL ELSE icd_10th_revision END,
    cause_recode_358 = CASE cause_recode_358 WHEN '' THEN NULL ELSE cause_recode_358 END,
    cause_recode_113 = CASE cause_recode_113 WHEN '' THEN NULL ELSE cause_recode_113 END,
    infant_cause_130 = CASE infant_cause_130 WHEN '' THEN NULL ELSE infant_cause_130 END,
    cause_recode_39 = CASE cause_recode_39 WHEN '' THEN NULL ELSE cause_recode_39 END,
    multiple_conditions = CASE multiple_conditions WHEN '' THEN NULL ELSE multiple_conditions END,
    number_of_entityaxis_conditions = CASE number_of_entityaxis_conditions WHEN '' THEN NULL ELSE number_of_entityaxis_conditions END,
    entityaxis_conditions_con = CASE entityaxis_conditions_con WHEN '' THEN NULL ELSE entityaxis_conditions_con END,
    entAx_condition_1st = CASE entAx_condition_1st WHEN '' THEN NULL ELSE entAx_condition_1st END,
    entAx_condition_2nd = CASE entAx_condition_2nd WHEN '' THEN NULL ELSE entAx_condition_2nd END,
    entAx_condition_3rd = CASE entAx_condition_3rd WHEN '' THEN NULL ELSE entAx_condition_3rd END,
    entAx_condition_4th = CASE entAx_condition_4th WHEN '' THEN NULL ELSE entAx_condition_4th END,
    entAx_condition_5th = CASE entAx_condition_5th WHEN '' THEN NULL ELSE entAx_condition_5th END,
    entAx_condition_6th = CASE entAx_condition_6th WHEN '' THEN NULL ELSE entAx_condition_6th END,
    entAx_condition_7th = CASE entAx_condition_7th WHEN '' THEN NULL ELSE entAx_condition_7th END,
    entAx_condition_8th = CASE entAx_condition_8th WHEN '' THEN NULL ELSE entAx_condition_8th END,
    entAx_condition_9th = CASE entAx_condition_9th WHEN '' THEN NULL ELSE entAx_condition_9th END,
    entAx_condition_10th = CASE entAx_condition_10th WHEN '' THEN NULL ELSE entAx_condition_10th END,
    entAx_condition_11th = CASE entAx_condition_11th WHEN '' THEN NULL ELSE entAx_condition_11th END,
    entAx_condition_12th = CASE entAx_condition_12th WHEN '' THEN NULL ELSE entAx_condition_12th END,
    entAx_condition_13th = CASE entAx_condition_13th WHEN '' THEN NULL ELSE entAx_condition_13th END,
    entAx_condition_14th = CASE entAx_condition_14th WHEN '' THEN NULL ELSE entAx_condition_14th END,
    entAx_condition_15th = CASE entAx_condition_15th WHEN '' THEN NULL ELSE entAx_condition_15th END,
    entAx_condition_16th = CASE entAx_condition_16th WHEN '' THEN NULL ELSE entAx_condition_16th END,
    entAx_condition_17th = CASE entAx_condition_17th WHEN '' THEN NULL ELSE entAx_condition_17th END,
    entAx_condition_18th = CASE entAx_condition_18th WHEN '' THEN NULL ELSE entAx_condition_18th END,
    entAx_condition_19th = CASE entAx_condition_19th WHEN '' THEN NULL ELSE entAx_condition_19th END,
    entAx_condition_20th = CASE entAx_condition_20th WHEN '' THEN NULL ELSE entAx_condition_20th END,
    number_of_recordaxis_conditions = CASE number_of_recordaxis_conditions WHEN '' THEN NULL ELSE number_of_recordaxis_conditions END,
    recordaxis_conditions = CASE recordaxis_conditions WHEN '' THEN NULL ELSE recordaxis_conditions END,
    recAx_condition_1st = CASE recAx_condition_1st WHEN '' THEN NULL ELSE recAx_condition_1st END,
    recAx_condition_2nd = CASE recAx_condition_2nd WHEN '' THEN NULL ELSE recAx_condition_2nd END,
    recAx_condition_3rd = CASE recAx_condition_3rd WHEN '' THEN NULL ELSE recAx_condition_3rd END,
    recAx_condition_4th = CASE recAx_condition_4th WHEN '' THEN NULL ELSE recAx_condition_4th END,
    recAx_condition_5th = CASE recAx_condition_5th WHEN '' THEN NULL ELSE recAx_condition_5th END,
    recAx_condition_6th = CASE recAx_condition_6th WHEN '' THEN NULL ELSE recAx_condition_6th END,
    recAx_condition_7th = CASE recAx_condition_7th WHEN '' THEN NULL ELSE recAx_condition_7th END,
    recAx_condition_8th = CASE recAx_condition_8th WHEN '' THEN NULL ELSE recAx_condition_8th END,
    recAx_condition_9th = CASE recAx_condition_9th WHEN '' THEN NULL ELSE recAx_condition_9th END,
    recAx_condition_10th = CASE recAx_condition_10th WHEN '' THEN NULL ELSE recAx_condition_10th END,
    recAx_condition_11th = CASE recAx_condition_11th WHEN '' THEN NULL ELSE recAx_condition_11th END,
    recAx_condition_12th = CASE recAx_condition_12th WHEN '' THEN NULL ELSE recAx_condition_12th END,
    recAx_condition_13th = CASE recAx_condition_13th WHEN '' THEN NULL ELSE recAx_condition_13th END,
    recAx_condition_14th = CASE recAx_condition_14th WHEN '' THEN NULL ELSE recAx_condition_14th END,
    recAx_condition_15th = CASE recAx_condition_15th WHEN '' THEN NULL ELSE recAx_condition_15th END,
    recAx_condition_16th = CASE recAx_condition_16th WHEN '' THEN NULL ELSE recAx_condition_16th END,
    recAx_condition_17th = CASE recAx_condition_17th WHEN '' THEN NULL ELSE recAx_condition_17th END,
    recAx_condition_18th = CASE recAx_condition_18th WHEN '' THEN NULL ELSE recAx_condition_18th END,
    recAx_condition_19th = CASE recAx_condition_19th WHEN '' THEN NULL ELSE recAx_condition_19th END,
    recAx_condition_20th = CASE recAx_condition_20th WHEN '' THEN NULL ELSE recAx_condition_20th END,
    bridged_race = CASE bridged_race WHEN '' THEN NULL ELSE bridged_race END,
    bridged_race_1 = CASE bridged_race_1 WHEN '' THEN NULL ELSE bridged_race_1 END,
    bridged_race_flag = CASE bridged_race_flag WHEN '' THEN NULL ELSE bridged_race_flag END,
    race_imputation_flag = CASE race_imputation_flag WHEN '' THEN NULL ELSE race_imputation_flag END,
    allother_races_imputed_2 = CASE allother_races_imputed_2 WHEN '' THEN NULL ELSE allother_races_imputed_2 END,
    bridged_race_recode_5 = CASE bridged_race_recode_5 WHEN '' THEN NULL ELSE bridged_race_recode_5 END,
    hispanicorigin = CASE hispanicorigin WHEN '' THEN NULL ELSE hispanicorigin END,
    hispanicorigin_bridgeracerecode = CASE hispanicorigin_bridgeracerecode WHEN '' THEN NULL ELSE hispanicorigin_bridgeracerecode END;
END$$
DELIMITER ;
SET SQL_SAFE_UPDATES = 1;

-- Update 2012 Empty strings [o]---------------------------------------------------------------------------
SET SQL_SAFE_UPDATES = 0;
DELIMITER $$
BEGIN$$
UPDATE
    cdcmortality.mortality_2012
SET
	person_id = CASE person_id WHEN '' THEN NULL ELSE person_id END,
    year_id = CASE year_id WHEN '' THEN NULL ELSE year_id END,
    resident_status = CASE resident_status WHEN '' THEN NULL ELSE resident_status END,
    edu = CASE edu WHEN '' THEN NULL ELSE edu END,
    edu_1989_rev = CASE edu_1989_rev WHEN '' THEN NULL ELSE edu_1989_rev END,
    edu_2003_rev = CASE edu_2003_rev WHEN '' THEN NULL ELSE edu_2003_rev END,
    edu_reporting_flag = CASE edu_reporting_flag WHEN '' THEN NULL ELSE edu_reporting_flag END,
    month_of_death = CASE month_of_death WHEN '' THEN NULL ELSE month_of_death END,
    sex = CASE sex WHEN '' THEN NULL ELSE sex END,
    reported_age_tmstmp_flag = CASE reported_age_tmstmp_flag WHEN '' THEN NULL ELSE reported_age_tmstmp_flag END,
    reported_age = CASE reported_age WHEN '' THEN NULL ELSE reported_age END,
    age_detail = CASE age_detail WHEN '' THEN NULL ELSE age_detail END,
    age_sub_flag = CASE age_sub_flag WHEN '' THEN NULL ELSE age_sub_flag END,
    age_recode_52 = CASE age_recode_52 WHEN '' THEN NULL ELSE age_recode_52 END,
    age_recode_27 = CASE age_recode_27 WHEN '' THEN NULL ELSE age_recode_27 END,
    age_recode_12 = CASE age_recode_12 WHEN '' THEN NULL ELSE age_recode_12 END,
    infant_age_recode_22 = CASE infant_age_recode_22 WHEN '' THEN NULL ELSE infant_age_recode_22 END,
    place_of_death_and_status = CASE place_of_death_and_status WHEN '' THEN NULL ELSE place_of_death_and_status END,
    marital_status = CASE marital_status WHEN '' THEN NULL ELSE marital_status END,
    day_of_week_of_death = CASE day_of_week_of_death WHEN '' THEN NULL ELSE day_of_week_of_death END,
    data_year = CASE data_year WHEN '' THEN NULL ELSE data_year END,
    injury_at_work = CASE injury_at_work WHEN '' THEN NULL ELSE injury_at_work END,
    manner_of_death = CASE manner_of_death WHEN '' THEN NULL ELSE manner_of_death END,
    method_of_disposition = CASE method_of_disposition WHEN '' THEN NULL ELSE method_of_disposition END,
    autopsy = CASE autopsy WHEN '' THEN NULL ELSE autopsy END,
    activity_code = CASE activity_code WHEN '' THEN NULL ELSE activity_code END,
    place_of_injury = CASE place_of_injury WHEN '' THEN NULL ELSE place_of_injury END,
    underlying_cause_of_death = CASE underlying_cause_of_death WHEN '' THEN NULL ELSE underlying_cause_of_death END,
    icd_10th_revision = CASE icd_10th_revision WHEN '' THEN NULL ELSE icd_10th_revision END,
    cause_recode_358 = CASE cause_recode_358 WHEN '' THEN NULL ELSE cause_recode_358 END,
    cause_recode_113 = CASE cause_recode_113 WHEN '' THEN NULL ELSE cause_recode_113 END,
    infant_cause_130 = CASE infant_cause_130 WHEN '' THEN NULL ELSE infant_cause_130 END,
    cause_recode_39 = CASE cause_recode_39 WHEN '' THEN NULL ELSE cause_recode_39 END,
    multiple_conditions = CASE multiple_conditions WHEN '' THEN NULL ELSE multiple_conditions END,
    number_of_entityaxis_conditions = CASE number_of_entityaxis_conditions WHEN '' THEN NULL ELSE number_of_entityaxis_conditions END,
    entityaxis_conditions_con = CASE entityaxis_conditions_con WHEN '' THEN NULL ELSE entityaxis_conditions_con END,
    entAx_condition_1st = CASE entAx_condition_1st WHEN '' THEN NULL ELSE entAx_condition_1st END,
    entAx_condition_2nd = CASE entAx_condition_2nd WHEN '' THEN NULL ELSE entAx_condition_2nd END,
    entAx_condition_3rd = CASE entAx_condition_3rd WHEN '' THEN NULL ELSE entAx_condition_3rd END,
    entAx_condition_4th = CASE entAx_condition_4th WHEN '' THEN NULL ELSE entAx_condition_4th END,
    entAx_condition_5th = CASE entAx_condition_5th WHEN '' THEN NULL ELSE entAx_condition_5th END,
    entAx_condition_6th = CASE entAx_condition_6th WHEN '' THEN NULL ELSE entAx_condition_6th END,
    entAx_condition_7th = CASE entAx_condition_7th WHEN '' THEN NULL ELSE entAx_condition_7th END,
    entAx_condition_8th = CASE entAx_condition_8th WHEN '' THEN NULL ELSE entAx_condition_8th END,
    entAx_condition_9th = CASE entAx_condition_9th WHEN '' THEN NULL ELSE entAx_condition_9th END,
    entAx_condition_10th = CASE entAx_condition_10th WHEN '' THEN NULL ELSE entAx_condition_10th END,
    entAx_condition_11th = CASE entAx_condition_11th WHEN '' THEN NULL ELSE entAx_condition_11th END,
    entAx_condition_12th = CASE entAx_condition_12th WHEN '' THEN NULL ELSE entAx_condition_12th END,
    entAx_condition_13th = CASE entAx_condition_13th WHEN '' THEN NULL ELSE entAx_condition_13th END,
    entAx_condition_14th = CASE entAx_condition_14th WHEN '' THEN NULL ELSE entAx_condition_14th END,
    entAx_condition_15th = CASE entAx_condition_15th WHEN '' THEN NULL ELSE entAx_condition_15th END,
    entAx_condition_16th = CASE entAx_condition_16th WHEN '' THEN NULL ELSE entAx_condition_16th END,
    entAx_condition_17th = CASE entAx_condition_17th WHEN '' THEN NULL ELSE entAx_condition_17th END,
    entAx_condition_18th = CASE entAx_condition_18th WHEN '' THEN NULL ELSE entAx_condition_18th END,
    entAx_condition_19th = CASE entAx_condition_19th WHEN '' THEN NULL ELSE entAx_condition_19th END,
    entAx_condition_20th = CASE entAx_condition_20th WHEN '' THEN NULL ELSE entAx_condition_20th END,
    number_of_recordaxis_conditions = CASE number_of_recordaxis_conditions WHEN '' THEN NULL ELSE number_of_recordaxis_conditions END,
    recordaxis_conditions = CASE recordaxis_conditions WHEN '' THEN NULL ELSE recordaxis_conditions END,
    recAx_condition_1st = CASE recAx_condition_1st WHEN '' THEN NULL ELSE recAx_condition_1st END,
    recAx_condition_2nd = CASE recAx_condition_2nd WHEN '' THEN NULL ELSE recAx_condition_2nd END,
    recAx_condition_3rd = CASE recAx_condition_3rd WHEN '' THEN NULL ELSE recAx_condition_3rd END,
    recAx_condition_4th = CASE recAx_condition_4th WHEN '' THEN NULL ELSE recAx_condition_4th END,
    recAx_condition_5th = CASE recAx_condition_5th WHEN '' THEN NULL ELSE recAx_condition_5th END,
    recAx_condition_6th = CASE recAx_condition_6th WHEN '' THEN NULL ELSE recAx_condition_6th END,
    recAx_condition_7th = CASE recAx_condition_7th WHEN '' THEN NULL ELSE recAx_condition_7th END,
    recAx_condition_8th = CASE recAx_condition_8th WHEN '' THEN NULL ELSE recAx_condition_8th END,
    recAx_condition_9th = CASE recAx_condition_9th WHEN '' THEN NULL ELSE recAx_condition_9th END,
    recAx_condition_10th = CASE recAx_condition_10th WHEN '' THEN NULL ELSE recAx_condition_10th END,
    recAx_condition_11th = CASE recAx_condition_11th WHEN '' THEN NULL ELSE recAx_condition_11th END,
    recAx_condition_12th = CASE recAx_condition_12th WHEN '' THEN NULL ELSE recAx_condition_12th END,
    recAx_condition_13th = CASE recAx_condition_13th WHEN '' THEN NULL ELSE recAx_condition_13th END,
    recAx_condition_14th = CASE recAx_condition_14th WHEN '' THEN NULL ELSE recAx_condition_14th END,
    recAx_condition_15th = CASE recAx_condition_15th WHEN '' THEN NULL ELSE recAx_condition_15th END,
    recAx_condition_16th = CASE recAx_condition_16th WHEN '' THEN NULL ELSE recAx_condition_16th END,
    recAx_condition_17th = CASE recAx_condition_17th WHEN '' THEN NULL ELSE recAx_condition_17th END,
    recAx_condition_18th = CASE recAx_condition_18th WHEN '' THEN NULL ELSE recAx_condition_18th END,
    recAx_condition_19th = CASE recAx_condition_19th WHEN '' THEN NULL ELSE recAx_condition_19th END,
    recAx_condition_20th = CASE recAx_condition_20th WHEN '' THEN NULL ELSE recAx_condition_20th END,
    bridged_race = CASE bridged_race WHEN '' THEN NULL ELSE bridged_race END,
    bridged_race_1 = CASE bridged_race_1 WHEN '' THEN NULL ELSE bridged_race_1 END,
    bridged_race_flag = CASE bridged_race_flag WHEN '' THEN NULL ELSE bridged_race_flag END,
    race_imputation_flag = CASE race_imputation_flag WHEN '' THEN NULL ELSE race_imputation_flag END,
    allother_races_imputed_2 = CASE allother_races_imputed_2 WHEN '' THEN NULL ELSE allother_races_imputed_2 END,
    bridged_race_recode_5 = CASE bridged_race_recode_5 WHEN '' THEN NULL ELSE bridged_race_recode_5 END,
    hispanicorigin = CASE hispanicorigin WHEN '' THEN NULL ELSE hispanicorigin END,
    hispanicorigin_bridgeracerecode = CASE hispanicorigin_bridgeracerecode WHEN '' THEN NULL ELSE hispanicorigin_bridgeracerecode END;
END$$
DELIMITER ;
SET SQL_SAFE_UPDATES = 1;

